### ISSUE TITLE
Third-Person POV Images for UnrealEgo Datasets

### ISSUE THREAD

**Issue by belgai** [hiroyasuakada/3D-Human-Pose-Perception-from-Egocentric-Stereo-Videos#1]
Hi,

First off, thank you for sharing this incredible work and making these valuable datasets available to the community!

I was wondering if it would be possible to provide third-person POV images corresponding to the UnrealEgo-RW Dataset and/or the UnrealEgo2 Dataset.

Thank you again for your efforts and contributions!

Best regards

**Comment by hiroyasuakada** [comment]
Hi, sorry for my late reply.

Unfortunately, I don't have third-person views now.
