### ISSUE TITLE
Help regarding SMPL parameters 

### ISSUE THREAD

**Issue by belgai** [hiroyasuakada/3D-Human-Pose-Perception-from-Egocentric-Stereo-Videos#2]
Hi @hiroyasuakada ,

Thank your very much for sharing this project and for releasing the datasets. Is it possible to get the SMPL parameters out of the output of the model?

Thanks a lot !

**Comment by hiroyasuakada** [comment]
Hi, sorry for my late reply.

Unfortunately, the current data and method do not support SMPL models.
